Repository hauler-dev/hauler, pull requests merged in 2024-09, with the labels that each got.

#322 bump to cosign v2.2.3-carbide.3 for new annotation
  .goreleaser.yaml
  Makefile
  cmd/hauler/cli/store/info.go
Labels: enhancement, size/M, dependencies

#320 enable docker load for hauler tarballs
  cmd/hauler/cli/store/save.go
  pkg/consts/consts.go
  pkg/content/oci.go
  pkg/store/store.go
Labels: enhancement, size/M

#324 use new annotation for 'store save' manifest.json
  cmd/hauler/cli/store/save.go
Labels: enhancement, size/S

#313 updated/standardize command descriptions
  cmd/hauler/cli/completion.go
  cmd/hauler/cli/login.go
  cmd/hauler/cli/store.go
  internal/flags/add.go
  internal/flags/copy.go
  internal/flags/extract.go
  internal/flags/info.go
  internal/flags/load.go
  internal/flags/login.go
  internal/flags/save.go
  internal/flags/serve.go
  internal/flags/store.go
  internal/flags/sync.go
Labels: documentation, enhancement

#329 add platform flag to store save
  cmd/hauler/cli/store/save.go
  internal/flags/save.go
Labels: enhancement, size/M

#328 bump: golang >= 1.23.1
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  Dockerfile
  go.mod
Labels: size/S, dependencies

#330 updates to fix build processes
  .goreleaser.yaml
  Dockerfile
Labels: enhancement, size/M

#331 fixed typo in hauler store save
  internal/flags/save.go
Labels: bug, size/S
