Repository hauler-dev/hauler, pull requests merged in 2024-06, with the labels that each got.

#247 Adding the timeout flag for fileserver command and setting default timeout to 60 seconds
  cmd/hauler/cli/store/serve.go
  internal/server/file.go
Labels: bug, size/S

#245 Configure chart commands to use helm clients for OCI and private regi…
  pkg/content/chart/chart.go
  pkg/content/chart/chart_test.go
Labels: enhancement, size/M

#240 Added some documentation text to sync command
  cmd/hauler/cli/store/sync.go
Labels: documentation, enhancement, size/S
