Repository hauler-dev/hauler, pull requests merged in 2024-10, with the labels that each got.

#332 added more fixes to github workflow
  .github/workflows/release.yaml
Labels: bug, size/S

#333 even more workflow fixes
  .github/workflows/release.yaml
  .goreleaser.yaml
  Makefile
Labels: bug, size/S

#334 yet another workflow goreleaser fix
  .goreleaser.yaml
Labels: bug, size/S

#335 have extract use proper ref from store info
  cmd/hauler/cli/store/extract.go
Labels: bug, enhancement, size/S

#336 improved workflow performance
  Dockerfile
  Makefile
Labels: bug, enhancement, size/S, dependencies

#337 trying new workflow build processes
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .goreleaser.yaml
  Makefile
Labels: bug, enhancement, size/M

#340 added timeout to goreleaser workflow
  Makefile
Labels: enhancement, size/S

#341 updated workflow to goreleaser builds
  .github/workflows/release.yaml
  .goreleaser.yaml
  Dockerfile
  Makefile
Labels: bug, enhancement, size/L

#344 [feature] build with boring crypto where available
  .goreleaser.yaml
  cmd/hauler/boringcrypto.go
Labels: enhancement
