Repository hauler-dev/hauler, pull requests merged in 2024-07, with the labels that each got.

#262 updated products flag description
  cmd/hauler/cli/store/sync.go
Labels: enhancement, size/S

#267 added debug container and workflow
  .github/workflows/release.yaml
  Dockerfile
Labels: enhancement, size/S

#271 removed some old references
  .github/workflows/release.yaml
  .github/workflows/unittest.yaml
  .goreleaser.yaml
  Makefile
  README.md
  install.sh
Labels: enhancement, size/M, dependencies

#274 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#279 updated goreleaser versioning defaults
  .goreleaser.yaml
Labels: enhancement, size/S

#278 fixed makefile for goreleaser v2 changes
  Makefile
Labels: bug, size/S

#277 feat: add readonly flag
  cmd/hauler/cli/store/serve.go
Labels: enhancement, size/S

#259 Fix digest images being lost on load of hauls (Signed).
  pkg/content/oci.go
Labels: bug, size/M
