Repository hauler-dev/hauler, pull requests merged in 2024-04, with the labels that each got.

#194 Make Product Registry configurable
  cmd/hauler/cli/store/sync.go
Labels: enhancement

#222 updated/cleaned github actions
  .github/workflows/release.yaml
  .github/workflows/unittest.yaml
Labels: enhancement, size/M

#223 fixed platforms in release workflow
  .github/workflows/release.yaml
Labels: bug

#224 fixed image ref in release workflow
  .github/workflows/release.yaml
Labels: bug

#225 removed tag in release workflow
  .github/workflows/release.yaml
Labels: bug

#227 helmifying hauler
  deploy/kubernetes/helm/charts/hauler/.helmignore
  deploy/kubernetes/helm/charts/hauler/Chart.yaml
  deploy/kubernetes/helm/charts/hauler/README.md
  deploy/kubernetes/helm/charts/hauler/app-readme.md
  deploy/kubernetes/helm/charts/hauler/templates/_helpers.tpl
  deploy/kubernetes/helm/charts/hauler/templates/hauler-fileserver/hauler-fileserver-deployment.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler-fileserver/hauler-fileserver-ingress.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler-fileserver/hauler-fileserver-service.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler-registry/hauler-registry-deployment.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler-registry/hauler-registry-ingress.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler-registry/hauler-registry-service.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler/hauler-jobs.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler/hauler-pvc.yaml
  deploy/kubernetes/helm/charts/hauler/templates/hauler/hauler-rbac.yaml
  deploy/kubernetes/helm/charts/hauler/values.yaml
Labels: enhancement, size/L

#229 removed vagrant scripts
  VAGRANT.md
  Vagrantfile
  vagrant-scripts/airgap.sh
  vagrant-scripts/k3s-install.sh
  vagrant-scripts/k3s-prep.sh
  vagrant-scripts/prep-all.sh
  vagrant-scripts/rke2-install.sh
  vagrant-scripts/rke2-prep.sh
Labels: bug, size/S
