Repository hauler-dev/hauler, pull requests merged in 2024-03, with the labels that each got.

#203 updated github files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yaml
  .github/workflows/unittest.yaml
Labels: enhancement, size/S

#207 updated and added new logos
  static/rgs-hauler-logo-icon.png
  static/rgs-hauler-logo-icon.svg
  static/rgs-hauler-logo-stacked.png
  static/rgs-hauler-logo-stacked.svg
  static/rgs-hauler-logo.png
  static/rgs-hauler-logo.svg
Labels: documentation, enhancement

#215 add container definition
  .dockerignore
  Dockerfile
Labels: enhancement, size/M

#216 update to v2.2.3 of RGS cosign fork
  .goreleaser.yaml
  Makefile
  pkg/artifacts/image/image.go
  pkg/cosign/cosign.go
Labels: enhancement, size/L

#217 better logging when adding to store
  cmd/hauler/cli/store/add.go
  cmd/hauler/cli/store/sync.go
  pkg/log/log.go
Labels: enhancement, size/M

#218 deprecate misleading cache flag from store
  cmd/hauler/cli/store/flags.go
Labels: bug, size/S
