Repository hauler-dev/hauler, pull requests merged in 2024-08, with the labels that each got.

#280 updated install script (`install.sh`)
  install.sh
Labels: bug, enhancement, size/S

#293 updated install.sh to remove github api
  install.sh
Labels: bug, size/S

#304 Updated cobra function for shell completion
  cmd/hauler/cli/completion.go
Labels: bug, size/S

#299 fixed hauler login typo
  cmd/hauler/cli/login.go
Labels: bug, size/S

#298 added list-repos flag
  cmd/hauler/cli/store/info.go
Labels: enhancement, size/S

#303 feat-273: TLS Flags
  .gitignore
  cmd/hauler/cli/cli.go
  cmd/hauler/cli/login.go
  cmd/hauler/cli/store.go
  cmd/hauler/cli/store/add.go
  cmd/hauler/cli/store/copy.go
  cmd/hauler/cli/store/extract.go
  cmd/hauler/cli/store/info.go
  cmd/hauler/cli/store/load.go
  cmd/hauler/cli/store/save.go
  cmd/hauler/cli/store/serve.go
  cmd/hauler/cli/store/sync.go
  internal/flags/add.go
  internal/flags/cli.go
  internal/flags/copy.go
  internal/flags/extract.go
  internal/flags/info.go
  internal/flags/load.go
  internal/flags/login.go
  internal/flags/save.go
  internal/flags/serve.go
  internal/flags/store.go
  internal/flags/sync.go
  internal/server/file.go
  internal/server/server.go
  pkg/consts/consts.go
Labels: enhancement, size/M

#311 github.com/rancherfederal/hauler => hauler.dev/go/hauler
  .github/workflows/pages.yaml
  .goreleaser.yaml
  cmd/hauler/cli/cli.go
  cmd/hauler/cli/login.go
  cmd/hauler/cli/store.go
  cmd/hauler/cli/store/add.go
  cmd/hauler/cli/store/copy.go
  cmd/hauler/cli/store/extract.go
  cmd/hauler/cli/store/info.go
  cmd/hauler/cli/store/load.go
  cmd/hauler/cli/store/save.go
  cmd/hauler/cli/store/serve.go
  cmd/hauler/cli/store/sync.go
  cmd/hauler/cli/version.go
  cmd/hauler/main.go
  go.mod
  internal/flags/store.go
  internal/mapper/mappers.go
  internal/server/file.go
  pkg/artifacts/config.go
  pkg/artifacts/file/file.go
  pkg/artifacts/file/file_test.go
  pkg/artifacts/file/getter/directory.go
  pkg/artifacts/file/getter/file.go
  pkg/artifacts/file/getter/getter.go
  pkg/artifacts/file/getter/getter_test.go
  pkg/artifacts/file/getter/https.go
  pkg/artifacts/file/options.go
  pkg/artifacts/image/image.go
  pkg/artifacts/memory/memory.go
  pkg/artifacts/memory/memory_test.go
  pkg/artifacts/memory/options.go
  pkg/collection/chart/chart.go
  pkg/collection/chart/dependents.go
  pkg/collection/imagetxt/imagetxt.go
  pkg/collection/imagetxt/imagetxt_test.go
  pkg/collection/k3s/k3s.go
  pkg/content/chart/chart.go
  pkg/content/chart/chart_test.go
  pkg/content/content.go
  pkg/content/oci.go
  pkg/cosign/cosign.go
  pkg/layer/cache.go
  pkg/layer/layer.go
  pkg/reference/reference_test.go
  pkg/store/store.go
  pkg/store/store_test.go
  static/go/hauler/index.html
Labels: enhancement, dependencies

#312 fixed `hauler completion` commands
  cmd/hauler/cli/completion.go
Labels: bug, size/S
