Repository hauler-dev/hauler, pull requests merged in 2025-01, with the labels that each got.

#378 cleaned up registry and improved logging
  cmd/hauler/cli/completion.go
  cmd/hauler/cli/store.go
  cmd/hauler/cli/store/add.go
  cmd/hauler/cli/store/copy.go
  cmd/hauler/cli/store/load.go
  cmd/hauler/cli/store/save.go
  cmd/hauler/cli/store/serve.go
  cmd/hauler/cli/store/sync.go
  go.mod
  internal/flags/serve.go
  internal/flags/store.go
  internal/server/registry.go
  pkg/apis/hauler.cattle.io/v1alpha1/groupversion_info.go
  pkg/cosign/cosign.go
  pkg/log/log.go
  pkg/reference/reference.go
Labels: enhancement, size/S

#384 replace mholt/archiver with mholt/archives
  cmd/hauler/cli/store/load.go
  cmd/hauler/cli/store/save.go
  go.mod
  go.sum
  pkg/archives/archiver.go
  pkg/archives/unarchiver.go
Labels: enhancement, size/M, dependencies

#390 use cosign v2.4.1+carbide.2 to address containerd annotation in index.json
  go.mod
  go.sum
Labels: bug, size/S
